apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nodejs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hello-world-nodejs
  template:
    metadata:
      labels:
        app: hello-world-nodejs
      annotations:
        buildTimestamp: "${{ steps.annotation.outputs.annotation }}"
    spec:
      containers:
      - name: hello-world-nodejs
        image: glentechdemoacr.azurecr.io/hello-world-nodejs:${{ steps.tag.outputs.tag }}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-nodejs
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: hello-world-nodejs
