name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: glentechdemoacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t glentechdemoacr.azurecr.io/hello-world-nodejs:latest .
          docker push glentechdemoacr.azurecr.io/hello-world-nodejs:latest

      - name: Deploy to AKS
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az aks get-credentials --resource-group GlentechDemoRG --name GlentechDemoAKS
          kubectl apply -f k8s-deployment.yaml

      - name: Delete old pods
        run: |
          kubectl delete pod -l app=hello-world-nodejs
